name: Sync Fork From DangKyToHop Repo

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/huynhducthanhtuan/DangKyToHop.git
          cd DangKyToHop
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add upstream https://github.com/hiengianguyen/DangKyToHop.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true
          git push origin main
